spring:
    datasource:
        author: sa
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:file:~/test;AUTO_SERVER=TRUE
    h2:
        console:
            enabled: true
            path: /h2
    jackson:
        serialization:
            write_dates_as_timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
keycloak:
    auth-server-url: http://localhost:9080/auth/
    resource: broken-blog-app
    realm: brokenblog
    public-client: true
    principal-attribute: preferred_username
    security-constraints:
        0:
            authRoles:
                - ROLE_USER
                - ROLE_MODERATOR
                - ROLE_ADMIN
            securityCollections:
                0:
                    methods:
                        - POST
                        - PUT
                        - DELETE
                    patterns:
                        - /api/v1/*


# this is what it would look like in properties:
#keycloak.security-constraints[0].authRoles[0]=user
#keycloak.security-constraints[0].authRoles[1]=moderator
#keycloak.security-constraints[0].authRoles[2]=admin
#keycloak.security-constraints[0].securityCollections[0].methods[0]=POST
#keycloak.security-constraints[0].securityCollections[0].methods[1]=PUT
#keycloak.security-constraints[0].securityCollections[0].methods[2]=DELETE
#keycloak.security-constraints[0].securityCollections[0].patterns[0]=/api/v1/*